export const dataProperties = [
  {
    id: 1,
    type: "Departamento",
    location: "Malecón de la Reserva, Miraflores",
    price: 450000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie1.jpeg",
    star: 4.9,
    meters: 150,
    description: "Espectacular departamento con vista frontal al mar. Acabados de lujo, ascensor directo y amplias terrazas para disfrutar del atardecer limeño.",
  },
  {
    id: 2,
    type: "Departamento",
    location: "El Golf, San Isidro",
    price: 850000,
    bedrooms: 4,
    bathroom: 4,
    image: "propertie2.jpeg",
    star: 5.0,
    meters: 320,
    description: "Exclusividad frente al Lima Golf Club. Amplios salones, cocina tipo isla con cuarzo y acabados en mármol. Máxima seguridad y privacidad.",
  },
  {
    id: 3,
    type: "Loft",
    location: "Sáenz Peña, Barranco",
    price: 320000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 4.8,
    meters: 95,
    description: "Loft de estilo bohemio en el corazón artístico de Barranco. Techos altos, ventanales de piso a techo y una ubicación estratégica cerca de galerías.",
  },
  {
    id: 4,
    type: "Departamento",
    location: "Chacarilla, Santiago de Surco",
    price: 280000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie4.jpeg",
    star: 4.5,
    meters: 140,
    description: "Departamento moderno en zona residencial tranquila. Cerca de parques y los mejores centros comerciales de Surco. Ideal para familias jóvenes.",
  },
  {
    id: 5,
    type: "Casa",
    location: "La Planicie, La Molina",
    price: 1200000,
    bedrooms: 5,
    bathroom: 6,
    image: "propertie5.jpeg",
    star: 4.9,
    meters: 600,
    description: "Impresionante casa con piscina, zona de BBQ y amplios jardines. Ubicada en la zona más exclusiva y segura de La Molina con clima de sol todo el año.",
  },
  {
    id: 6,
    type: "Flat",
    location: "Av. Pardo, Miraflores",
    price: 210000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie6.jpeg",
    star: 4.2,
    meters: 85,
    description: "Flat funcional en excelente estado. Ubicación céntrica con acceso rápido a bancos, restaurantes y áreas recreativas.",
  },
  {
    id: 7,
    type: "Departamento",
    location: "San Borja Sur, San Borja",
    price: 265000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie7.jpeg",
    star: 4.6,
    meters: 130,
    description: "Departamento con vista a parque. Zona muy segura, ideal para hacer deporte y pasear en familia. Incluye dos cocheras lineales.",
  },
  {
    id: 8,
    type: "Casa",
    location: "Casuarinas, Santiago de Surco",
    price: 1500000,
    bedrooms: 5,
    bathroom: 5,
    image: "propertie8.jpeg",
    star: 5.0,
    meters: 850,
    description: "Residencia de súper lujo con vista panorámica a toda la ciudad de Lima. Acabados importados y sistema de casa inteligente.",
  },
  {
    id: 9,
    type: "Departamento",
    location: "Pezet, San Isidro",
    price: 720000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie9.jpeg",
    star: 4.7,
    meters: 210,
    description: "Elegancia en la zona más exclusiva de Pezet. Áreas comunes de primer nivel: gimnasio, piscina temperada y sala de reuniones.",
  },
  {
    id: 10,
    type: "Penthouse",
    location: "Cerros de Camacho, Surco",
    price: 550000,
    bedrooms: 3,
    bathroom: 4,
    image: "propertie10.jpeg",
    star: 4.4,
    meters: 250,
    description: "Penthouse con vista al Club El Golf Los Incas. Amplia terraza privada y acabados en madera estructurada.",
  },
  {
    id: 11,
    type: "Departamento",
    location: "Cerca al Parque Kennedy, Miraflores",
    price: 185000,
    bedrooms: 1,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 4.3,
    meters: 65,
    description: "Moderno departamento de 1 dormitorio, ideal para inversión o Airbnb. Equipado con áreas sociales modernas.",
  },
  {
    id: 12,
    type: "Casa",
    location: "Rinconada del Lago, La Molina",
    price: 890000,
    bedrooms: 4,
    bathroom: 4,
    image: "propertie12.jpeg",
    star: 4.8,
    meters: 450,
    description: "Casa estilo contemporáneo dentro de condominio cerrado. Seguridad 24/7 y un entorno rodeado de naturaleza.",
  },
  {
    id: 13,
    type: "Departamento",
    location: "Barranco Tradicional",
    price: 295000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie13.jpeg",
    star: 4.5,
    meters: 110,
    description: "Vive cerca del Puente de los Suspiros. Departamento con balcón, excelente iluminación natural y pisos de parquet original.",
  },
  {
    id: 14,
    type: "Departamento",
    location: "Santa Cruz, Miraflores",
    price: 340000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie14.jpeg",
    star: 4.6,
    meters: 125,
    description: "En la zona gastronómica de Miraflores. Edificio eco-amigable con estacionamiento para bicicletas y zona de parrillas.",
  },
  {
    id: 15,
    type: "Departamento",
    location: "Aurora, Miraflores",
    price: 380000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie15.jpeg",
    star: 4.7,
    meters: 160,
    description: "Ubicado en la mejor zona residencial de Miraflores. Amplia sala comedor con vista externa a parque privado.",
  },
  {
    id: 16,
    type: "Departamento",
    location: "Corpac, San Isidro",
    price: 240000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie16.jpeg",
    star: 4.1,
    meters: 115,
    description: "Cerca al centro financiero. Departamento céntrico, ideal para ejecutivos, con excelente distribución de ambientes.",
  },
  {
    id: 17,
    type: "Casa",
    location: "Las Lagunas, La Molina",
    price: 950000,
    bedrooms: 4,
    bathroom: 5,
    image: "propertie17.jpeg",
    star: 4.8,
    meters: 520,
    description: "Residencia frente a la laguna. Muelle privado, terraza amplia y acabados en granito y madera caoba.",
  },
  {
    id: 18,
    type: "Departamento",
    location: "Valle Hermoso, Surco",
    price: 225000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie18.jpeg",
    star: 4.3,
    meters: 120,
    description: "Departamento en zona muy tranquila, cerca de colegios prestigiosos. Ideal para la comodidad de tu familia.",
  },
  {
    id: 19,
    type: "Departamento",
    location: "Dasso, San Isidro",
    price: 600000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie19.jpeg",
    star: 4.9,
    meters: 190,
    description: "A pasos de las mejores boutiques de San Isidro. Edificio clásico remodelado con estándares modernos de alta gama.",
  },
  {
    id: 20,
    type: "Departamento",
    location: "Malecon Armendariz, Miraflores",
    price: 490000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie20.jpeg",
    star: 4.7,
    meters: 175,
    description: "Vista espectacular a la bajada de Armendáriz. Terraza amplia, dormitorios con baño incorporado y acabados de primera.",
  },
  {
    id: 21,
    type: "Casa",
    location: "Sol de La Molina, La Molina",
    price: 680000,
    bedrooms: 4,
    bathroom: 4,
    image: "propertie21.jpeg",
    star: 4.5,
    meters: 350,
    description: "Casa moderna de estreno. Amplia cocina equipada, sala de estar y un jardín posterior con espacio para piscina.",
  },
  {
    id: 22,
    type: "Departamento",
    location: "Higuereta, Surco",
    price: 195000,
    bedrooms: 3,
    bathroom: 2,
    image: "propertie22.jpeg",
    star: 4.0,
    meters: 105,
    description: "Departamento con excelente conectividad a avenidas principales. Muy bien iluminado y mantenido.",
  },
  {
    id: 23,
    type: "Dúplex",
    location: "San Borja Norte, San Borja",
    price: 310000,
    bedrooms: 3,
    bathroom: 3,
    image: "propertie23.jpeg",
    star: 4.6,
    meters: 145,
    description: "Departamento dúplex con terraza propia y área de lavandería independiente. Cerca al Pentagonito.",
  },
  {
    id: 24,
    type: "Departamento",
    location: "Barranco Cliffside",
    price: 420000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie24.jpeg",
    star: 4.9,
    meters: 120,
    description: "Ubicación privilegiada en el acantilado de Barranco. Diseño arquitectónico de vanguardia y vistas infinitas al mar.",
  },
];